# Generated by Django 3.2.10 on 2022-09-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
