# Generated by Django 3.2.10 on 2022-09-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_viewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-viewed']},
        ),
    ]
